title: Polskija staronki
url: https://freedombel.github.io
baseurl: /pl-pages
remote_theme: riggraz/no-style-please
repository: freedombel/pl-pages

theme_config:
  appearance: "auto"
  back_home_text: ".. nazad"
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
